spring:
  application:
    name: authentication-service
  security:
    user:
      name: pankaj
      password: password
  datasource:
    url: jdbc:postgresql://localhost:5433/security-app
    username: pankaj
    password:

